[model]
training = true
config = "ModelConfig(input_size=3, hidden_size=300, num_layers=3, output_size=20, dropout=0.1, conv_out_channels=16, kernel_size=3, conv_padding='same', conv_dropout=0.1)"

[types]
training = "bool"
config = "ModelConfig"
