[experiment]
name = "hymenoptera_classification"

[model]
model_type = ["cnn"]
hidden_size = [32, 64, 128]
num_layers = [1, 2, 3]
dropout = [0.1, 0.4]
lr = [1e-4, 1e-2]
batch_size = [8, 16, 32]
num_classes = 2  # Bees vs Ants!
image_size = 224
transfer_custom_layers = [1, 2, 3]

[data]
augment = true
resize_size = 256
crop_size = 224

[training]
epochs = 5
print_every = 10

[tune]
num_samples = 10
max_concurrent_trials = 1