[experiment]
name = "hymenoptera_classification_transfer_zoom"

[model]
model_type = ["cnn"]
hidden_size = [16, 32, 64] #verkleind op basis van vorige experimenten
num_layers = [3, 4, 5] #verkleind obv vorige experimenten
growth_factor = [1.5, 2.0]  # Hoe snel channels groeien
max_channels = [128, 256] 
dropout = [0.2, 0.5]
lr = [1e-4, 1e-3]
batch_size = [4, 8, 16] #klein vanwege grootte
num_classes = 2  # Bees vs Ants!
image_size = 224
transfer_custom_layers = [1, 2]

[data]
augment = true
resize_size = 256
crop_size = 224

[training]
epochs = 20  
patience = 5  # Stop na 5 epochs zonder verbetering
scheduler_step = 3  # Verlaag learning rate elke 3 epochs
scheduler_gamma = 0.5  # Halveer learning rate

[tune]
num_samples = 10
max_concurrent_trials = 1