[experiment]
name = "cnn_flower_search"

[model]
model_type = ["cnn"]
hidden_size = [32, 64, 128]
num_layers = [1, 2, 3]
dropout = [0.1, 0.4]
lr = [1e-5, 1e-2]
batch_size = [16, 32]
num_classes = 102
image_size = 224
transfer_custom_layers = [1, 2, 3]

[data]
augment = true
resize_size = 256
crop_size = 224

[tune]
num_samples = 20