[model]
training = true
in_channels = 1
input_size = [64, 1, 28, 28]
filters = 128
units1 = 256
units2 = 256
units3 = 256

[types]
training = "bool"
in_channels = "int"
input_size = "tuple"
filters = "int"
units1 = "int"
units2 = "int"
units3 = "int"
