[model]
training = true
[model.config]
matrixshape = [28, 28]
batchsize = 64
input_channels = 1
hidden = 96
kernel_size = 2
maxpool = 3
num_layers = 2
num_classes = 10


[types]
training = "bool"
config = "dict"
