[model]
epochs = 10
metrics = ["Accuracy"]
logdir = "/home/azureuser/MADS-ML-AdriaanS/models"
train_steps = 937
valid_steps = 156
reporttypes = ["ReportTypes.MLFLOW", "ReportTypes.TOML"]
[model.optimizer_kwargs]
lr = 0.001
weight_decay = 1e-05

[model.scheduler_kwargs]
factor = 0.1
patience = 10

[model.earlystop_kwargs]
save = false
verbose = true
patience = 10


[types]
epochs = "int"
metrics = "list"
logdir = "PosixPath"
train_steps = "int"
valid_steps = "int"
reporttypes = "list"
optimizer_kwargs = "dict"
scheduler_kwargs = "dict"
earlystop_kwargs = "dict"
