[model]
training = true
[model.config]
matrixshape = [28, 28]
batchsize = 64
input_channels = 1
hidden = 48
kernel_size = 3
maxpool = 3
num_layers = 5
num_classes = 10


[types]
training = "bool"
config = "dict"
