[model]
name = "CNN"
type = "PyTorch"

[training]
batchsize = 64
epochs = 20
optimizer = "Adam"
loss_function = "CrossEntropyLoss"
device = "cpu"
train_steps = 937
valid_steps = 937

[performance]
test_loss = 0.2757310732451676
training_time = "2025-05-08 17:20:09.315657"

[metadata]
created_at = "2025-05-08T17:20:09.315674"
mlflow_run_id = "83c68b334d0d4dc8987e1f8a137da0e6"
developer = "adriaan"

[model.architecture]
filters = 56
units1 = 88
units2 = 112
input_channels = 1
input_size = [ 32, 1, 28, 28,]
